apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secret
  namespace: flask-app-ns

type: Opaque
data:
  MYSQL_USER: YWRtaW4=       #base64 encoded : echo -n "user" | base64
  MYSQL_PASSWORD: YWRtaW4wNDA2       #base64 encoded : echo -n "password" | base64