apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
  namespace: flask-app-ns

spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer